[package]
name = "gomoku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#relm4 = "0.6.0"
#regex-lite = "0.1.5"
bincode = "1.3.3"
serde = { version = "1.0.193", features = ["derive"] }
